version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel-vue-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel-vue-nginx
    ports:
      - "8081:80" # Changed from 8080 to 8081
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-vue-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306" # Use port 3307 to avoid conflicts
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
